version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # .env 파일에서 환경 변수 불러오기
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GEMINI_API_KEY=$AIzaSyCbRHVairhTvJLuctfxz7xhCS3eeGzjij8
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload